//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class demande
    {
        public int id_demande { get; set; }
        public Nullable<int> id_equip { get; set; }
        public Nullable<int> id_typentr { get; set; }
        public Nullable<int> etat { get; set; }
        public Nullable<System.DateTime> date_dem { get; set; }
    
        public virtual type_entretien type_entretien { get; set; }
    }
}
