//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class intervention
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public intervention()
        {
            this.piece = new HashSet<piece>();
        }
    
        public int id_inter { get; set; }
        public Nullable<int> id_equip { get; set; }
        public Nullable<int> id_typenter { get; set; }
        public Nullable<int> nb_min { get; set; }
        public string typenter { get; set; }
        public Nullable<System.DateTime> date_inter { get; set; }
    
        public virtual equipement equipement { get; set; }
        public virtual type_entretien type_entretien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<piece> piece { get; set; }
    }
}
