//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class piece
    {
        public int id_piece { get; set; }
        public Nullable<int> id_inter { get; set; }
        public string libellep { get; set; }
        public Nullable<double> valeur { get; set; }
    
        public virtual intervention intervention { get; set; }
    }
}
